CPPFLAGS = -I .
CFLAGS =-g -std=gnu99 -O1 -Wall
CXXFLAGS = -g -std=gnu++17 -O1 -Wall
#LDFLAGS +=
LDFLAGS += -static
LDLIBS += -lrt -lpthread
#LDLIBS += -lm

SOURCES = src/main.cpp src/math/vector.cpp src/math/matrix.cpp src/mz_apo/mzapo_phys.c src/mz_apo/mzapo_parlcd.c src/mz_apo/serialize_lock.c src/peripherals/input.cpp src/geometry/cube.cpp src/geometry/camera.cpp src/peripherals/mapping.cpp src/math/utils.cpp src/graphics/color.cpp src/peripherals/output.cpp src/graphics/screen.cpp src/peripherals/utils.cpp src/graphics/menu.cpp src/render/renderer.cpp src/render/transform_2d.cpp src/render/transform_3d.cpp src/mz_apo/font_types.h src/mz_apo/font_prop14x16.c src/geometry/face.cpp
TARGET_EXE = apo_cube

# ===================== Main Build =====================
#TARGET_IP ?= 192.168.202.127
ifeq ($(TARGET_IP),)
ifneq ($(filter debug run,$(MAKECMDGOALS)),)
$(warning The target IP address is not set)
$(warning Run as "TARGET_IP=192.168.202.xxx make run" or modify Makefile)
endif
endif
TARGET_DIR ?= /tmp/$(shell whoami)
TARGET_USER ?= root
# for use from Eduroam network use TARGET_IP=localhost and enable next line
#SSH_OPTIONS=-o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "Port=2222"
#SSH_GDB_TUNNEL_REQUIRED=y
#SSH_OPTIONS=-i /opt/zynq/ssh-connect/mzapo-root-key

OBJECTS += $(filter %.o,$(SOURCES:%.c=%.o))
OBJECTS += $(filter %.o,$(SOURCES:%.cpp=%.o))

#$(warning OBJECTS=$(OBJECTS))

ifeq ($(filter %.cpp,$(SOURCES)),)
LINKER = $(CC)
LDFLAGS += $(CFLAGS) $(CPPFLAGS)
else
LINKER = $(CXX)
LDFLAGS += $(CXXFLAGS) $(CPPFLAGS)
endif

%.o:%.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<

%.o:%.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ -c $<

all: $(TARGET_EXE)

$(TARGET_EXE): $(OBJECTS)
	$(LINKER) $(LDFLAGS) -L. $^ -o $@ $(LDLIBS)

.PHONY : dep all run copy-executable debug

dep: depend

depend: $(SOURCES) *.h
	echo '# autogenerated dependencies' > depend
ifneq ($(filter %.c,$(SOURCES)),)
	$(CC) $(CFLAGS) $(CPPFLAGS) -w -E -M $(filter %.c,$(SOURCES)) \
	  >> depend
endif
ifneq ($(filter %.cpp,$(SOURCES)),)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -w -E -M $(filter %.cpp,$(SOURCES)) \
	  >> depend
endif

clean:
	rm -f *.o *.a $(OBJECTS) $(TARGET_EXE) connect.gdb depend

copy-executable: $(TARGET_EXE)
	ssh $(SSH_OPTIONS) -t $(TARGET_USER)@$(TARGET_IP) killall gdbserver 1>/dev/null 2>/dev/null || true
	ssh $(SSH_OPTIONS) $(TARGET_USER)@$(TARGET_IP) mkdir -p $(TARGET_DIR)
	scp $(SSH_OPTIONS) $(TARGET_EXE) $(TARGET_USER)@$(TARGET_IP):$(TARGET_DIR)/$(TARGET_EXE)

run: copy-executable $(TARGET_EXE)
	ssh $(SSH_OPTIONS) -t $(TARGET_USER)@$(TARGET_IP) $(TARGET_DIR)/$(TARGET_EXE)

ifneq ($(filter -o ProxyJump=,$(SSH_OPTIONS))$(SSH_GDB_TUNNEL_REQUIRED),)
SSH_GDB_PORT_FORWARD=-L 12345:127.0.0.1:12345
TARGET_GDB_PORT=127.0.0.1:12345
else
TARGET_GDB_PORT=$(TARGET_IP):12345
endif

debug: copy-executable $(TARGET_EXE)
	xterm -e ssh $(SSH_OPTIONS) $(SSH_GDB_PORT_FORWARD) -t $(TARGET_USER)@$(TARGET_IP) gdbserver :12345 $(TARGET_DIR)/$(TARGET_EXE) &
	sleep 2
	echo >connect.gdb "target extended-remote $(TARGET_GDB_PORT)"
	echo >>connect.gdb "b main"
	echo >>connect.gdb "c"
	ddd --debugger gdb-multiarch -x connect.gdb $(TARGET_EXE)

# ===================== Virtual Build (runv) =====================
runv_SRC = src/main.cpp src/virtual_peripherals/input.cpp src/virtual_peripherals/output.cpp src/virtual_peripherals/mapping.cpp src/virtual_peripherals/utils.cpp src/geometry/cube.cpp src/geometry/face.cpp src/geometry/camera.cpp src/math/vector.cpp src/math/matrix.cpp src/math/utils.cpp src/graphics/color.cpp src/graphics/screen.cpp src/render/renderer.cpp src/render/transform_2d.cpp src/render/transform_3d.cpp src/graphics/menu.cpp src/mz_apo/font_types.h src/mz_apo/font_prop14x16.c
runv_TARGET = apo_cube_virtual
runv_CXX = g++
runv_CXXFLAGS = -Wall -g -DVIRTUAL_PERIPHERALS

runv:
	$(runv_CXX) $(runv_CXXFLAGS) $(runv_SRC) -o $(runv_TARGET)
	./$(runv_TARGET)

buildv:
	$(runv_CXX) $(runv_CXXFLAGS) $(runv_SRC) -o $(runv_TARGET)

executev:
	./$(runv_TARGET)

cleanv:
	rm -f $(runv_TARGET)

-include depend
